goldmark:
  renderer:
    unsafe: true

  extensions:
    extras:
      delete:
        enable: true
      superscript:
        enable: true
      insert:
        enable: true
      subscript:
        enable: true
      mark:
        enable: true
    strikethrough: false

    passthrough:
      enable: true
      delimiters:
        block:
          - - \[
            - \]
          - - $$
            - $$
        inline:
          - - \(
            - \)

tableOfContents:
  endLevel: 4
  ordered: true
  startLevel: 2

highlight:
  noClasses: false
  codeFences: true
  guessSyntax: true
  lineNoStart: 1
  lineNos: true
  lineNumbersInTable: true
  tabWidth: 4
