main:
  - name: Home
    url: /
    weight: 1
    params:
      icon: home
  - name: Buy Me Coffee
    url: https://www.buymeacoffee.com/mirumodapon
    params:
      icon: pi-coffee

social:
  - name: GitHub
    url: https://github.com/mirumodapon
    params:
      icon: brand-github
      newTab: true
  - name: Instagram
    url: https://www.instagram.com/mirumo_0915
    params:
      icon: brand-instagram
      newTab: true
  - name: Mail
    url: mailto:mail@miru.cc
    params:
      icon: mail
